package it.unibz.inf.data_pumper.core.main.test;

import org.junit.Test;

import it.unibz.inf.data_pumper.core.main.Main;
import junit.framework.TestCase;

/**
 * The class <code>MainTest</code> contains tests for the class {@link
 * <code>Main</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 3/19/15 2:11 PM
 *
 * @author tir
 *
 * @version $Revision$
 */
public class MainTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public MainTest(String name) {
		super(name);
	}
	
	@Test
	public void testMain(){
		String[] args = new String[2];
		Main.main(args);
		
		
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = it.unibz.inf.data_pumper.core.main.test
 * package.sourceFolder = dataPumper/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = MainTest
 * testClassType = it.unibz.inf.data_pumper.core.main.Main
 */